---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Create an RDS PostgreSQL 15 database instance on a designated data subnet. Use AWS Secrets Manager to securely store the database credentials 

Parameters:
 DBInstanceIdentifier:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: The instance name should begin with a letter and should contain only alphanumerics
  # Default: mypostgresinstance
  Description: Name of the instance identifier 
  MaxLength: 60
  MinLength: 1
  Type: String

 DBName:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: The DB name should begin with a letter and should contain only alphanumerics
  # Default: testdb1
  Description: Postgres database name
  MaxLength: 64
  MinLength: 1
  Type: String

 MasterUsername:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: The DB username should begin with a letter and should contain only alphanumerics
  # Default: masteruser
  Description: Username for postgres database access
  MaxLength: 16
  MinLength: 1
  NoEcho: true
  Type: String

 MasterUserPassword:
  AllowedPattern: '[a-zA-Z0-9]*'
  ConstraintDescription: The db passoword should contain only alphanumerics
  # Default: masteruser
  Description: Password for postgres database masteruser
  MaxLength: 41
  MinLength: 8
  NoEcho: true
  Type: String
 
 BackupRetentionPeriod:
  ConstraintDescription: DB backup retention period should be between 0 and 35 days
  # Default: 0
  Description: The number of days for which the automatic DB snapshots are retained
  MaxValue: 35
  MinValue: 0
  Type: Number

 AllocatedStorage:
  ConstraintDescription: The size allocated for the instance should between 5 and 1024Gb
  # Default: 20
  Description: The size of the instance in Gb
  MaxValue: 65536
  MinValue: 5
  Type: Number

 DBInstanceClass:
  AllowedValues:
   - db.t3.2xlarge
   - db.t3.xlarge
   - db.t3.large
   - db.t3.medium
   - db.t3.small
   - db.t3.micro
  ConstraintDescription: Select a valid database instance type
  # Default: db.t3.micro
  Description: The database instance type
  Type: String

 MultiAZ:
  AllowedValues:
   - true
   - false
  ConstraintDescription: Select either true or false
  # Default: false
  Description: Creates a Multi-AZ Postgres Amazon RDS instance
  Type: String

 Engine:
  # AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: Databse to use
  # Default: postgres
  Description: The name of the database engine that you want to use for this DB instance
  Type: String

 EngineVersion:
  # AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: database version should be valid
  # Default: "15"
  Description: The version number of the database engine to use.
  Type: String

 AvailabilityZone:
   Description: The availability zone for the RDS instance
  #  Default: ap-south-2a
   Type: String

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      # DBSubnetGroupName: MyDBSubnetGroup
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds:
        # - !ImportValue OtherStack-SubnetId1
        - !ImportValue DBSubnetId
        # - !ImportValue !Sub "${AWS::StackName}-DBSubnetId"
        # - !ImportValue PrivateSubnet2Id
        # - subnet-87654321

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AvailabilityZone: !Ref AvailabilityZone
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroup 
      MultiAZ: !Ref MultiAZ 
      VPCSecurityGroups: !Ref DBSecurityGroup

# Outputs:
#   set of outputs
