---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Create an RDS PostgreSQL 15 database instance on a designated data subnet. Use AWS Secrets Manager to securely store the database credentials 

Parameters:
  MyDBSecret:
    Description: name of secrest manager
    Default: 'MyDBSecret'
    Type: String
  DBMasterUsername:
    Description: Username for PostgreSQL database access
    Default: 'masteruser'
    Type: String


Resources:
  MyDatabaseSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "Secret for PostgreSQL database credentials"
      Name: MyDatabaseSecret #secret name
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}' 
        GenerateStringKey: "password"
        PasswordLength: 12
        ExcludeCharacters: '"@/\'

Outputs:
  DatabaseSecretARN:
    Description: "ARN of the created PostgreSQL database secret"
    Value: !Ref MyDatabaseSecret
    Export:
      Name: "DatabaseSecretARN" 


