---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  creating ecs with 2 service. one service runs application and other runs database. 

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:  
      - Label:  
          default: VPC Parameters 
        Parameters: 
         - VpcCIDRBlock 
         - PublicSubnet1CidrBlock
         - PublicSubnet2CidrBlock
         - PrivateSubnet1CidrBlock
         - PrivateSubnet2CidrBlock

      # - Label:  
      #     default: DB Parameters 
      #   Parameters: 
      #    - DBInstanceIdentifier 
      #    - DBName 
      #    - MasterUsername 
      #    - MasterUserPassword 
      #    - EngineVersion 
      #    - BackupRetentionPeriod 
      #    - AllocatedStorage 
      #    - DBInstanceClass 
      #    - MultiAZ

Parameters:
  VpcCIDRBlock:
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    Type: String
  PublicSubnet1CidrBlock:
    Description: CIDR block for the public subnet 1
    Default: 10.0.1.0/24
    Type: String
  PublicSubnet2CidrBlock:
    Description: CIDR block for the public subnet 2
    Default: 10.0.2.0/24
    Type: String
  PrivateSubnet1CidrBlock:
    Description: CIDR block for the private subnet 1
    Default: 10.0.3.0/24
    Type: String
  PrivateSubnet2CidrBlock:
    Description: CIDR block for the private subnet 2
    Default: 10.0.4.0/24
    Type: String
  

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-exam-paranjay.s3.ap-south-1.amazonaws.com/network-stack.yml
      Parameters:
        VpcCIDRBlock: !Ref VpcCIDRBlock
        
  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      TemplateURL: #https://cloudformation-exam-paranjay.s3.ap-south-1.amazonaws.com/RDS.yml
      Parameters:  
        AllocatedStorage: !Ref AllocatedStorage


# Outputs:
#   set of outputs

