---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  creating ecs with 2 service. one service runs application and other runs database. 

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:  
      - Label:  
          default: VPC Parameters 
        Parameters: 
         - VpcCIDRBlock 
         - PublicSubnet1CidrBlock
         - PublicSubnet2CidrBlock
         - PrivateSubnet1CidrBlock
         - PrivateSubnet2CidrBlock

      # - Label:  
      #     default: DB Parameters 
      #   Parameters: 
      #    - DBInstanceIdentifier 
      #    - DBName 
      #    - MasterUsername 
      #    - MasterUserPassword 
      #    - EngineVersion 
      #    - BackupRetentionPeriod 
      #    - AllocatedStorage 
      #    - DBInstanceClass 
      #    - MultiAZ

Parameters:
  ###############  VPC   ######################
  VpcCIDRBlock:
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    Type: String
  PublicSubnet1CidrBlock:
    Description: CIDR block for the public subnet 1
    Default: 10.0.1.0/24
    Type: String
  PublicSubnet2CidrBlock:
    Description: CIDR block for the public subnet 2
    Default: 10.0.2.0/24
    Type: String
  PrivateSubnet1CidrBlock:
    Description: CIDR block for the private subnet 1
    Default: 10.0.3.0/24
    Type: String
  PrivateSubnet2CidrBlock:
    Description: CIDR block for the private subnet 2
    Default: 10.0.4.0/24
    Type: String

  ###################   ECS   ######################
  ECSClusterName:
    Type: String
    Default: ecs-tutorial
  ECSServiceName:
    Type: String
    Default: ecs-tutorial-td
  LoadBalancerName:
    Type: String
    Default: ecs-tutorial-lb

  ################   PARAMETERS   ###################
  ParameterStoreUser:
    Type: String
    Default: logicwind
  ParameterStorePassword:
    Type: String
    Default: logicwind
  

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-exam-paranjay.s3.ap-south-1.amazonaws.com/network-stack.yml
      Parameters:
        VpcCIDRBlock: !Ref VpcCIDRBlock
        PublicSubnet1CidrBlock: !Ref PublicSubnet1CidrBlock
        PublicSubnet2CidrBlock: !Ref PublicSubnet2CidrBlock
        PrivateSubnet1CidrBlock: !Ref PrivateSubnet1CidrBlock
        PrivateSubnet2CidrBlock: !Ref PrivateSubnet2CidrBlock
        
  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      TemplateURL: #https://cloudformation-exam-paranjay.s3.ap-south-1.amazonaws.com/RDS.yml
      Parameters:  
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref ECSServiceName
        LoadBalancerName: !Ref LoadBalancerName

  ParameterStore:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #https://cloudformation-exam-paranjay.s3.ap-south-1.amazonaws.com/RDS.yml
      Parameters:  
        ParameterStoreUser: !Ref ParameterStoreUser
        ParameterStorePassword: !Ref ParameterStorePassword
       
